require("core.options")
require("core.lazy")
require("core.autostart")
require("core.keymaps")
require("core.colorscheme")
-- require("core.lsp")
-- require("plugins.comment")
-- require("plugins.treesitter")
-- require("plugins.neo-tree")
-- -- require("zeroknots.plugins.lualine")
-- require("plugins.lualineSlanted")
-- require("plugins.telescope")
-- require("plugins.nvim-cmp")
-- require("plugins.lsp.mason")
-- require("plugins.lsp.lspsaga")
-- require("plugins.lsp.lspconfig")
-- require("plugins.lsp.null-ls")
-- require("plugins.autopairs")
-- require("plugins.illuminate")
-- require("plugins.gitsigns")
-- require("plugins.rainbow")
-- require("plugins.transparent")
-- require("plugins.glance")
-- require("plugins.lsp.lsplines")
-- require("plugins.lsp.null-ls")
-- require("plugins.autopairs")
-- require("plugins.illuminate")
-- require("plugins.dracula")
-- require("plugins.gitblame")
-- require("plugins.betterescape")
-- require("plugins.lf")
-- require("plugins.coverage")
-- -- require("themes.monokaipro")
-- require("plugins.lsp.lsp")
-- require("zeroknots.plugins.lsp.lspsignatures")
-- require("zeroknots.plugins.lsp.navic")
