require("zeroknots.plugins-setup")
require("zeroknots.core.autostart")
require("zeroknots.core.options")
require("zeroknots.core.keymaps")
require("zeroknots.core.colorscheme")
require("zeroknots.plugins.comment")
require("zeroknots.plugins.treesitter")
require("zeroknots.plugins.neo-tree")
-- require("zeroknots.plugins.lualine")
require("zeroknots.plugins.lualineSlanted")
require("zeroknots.plugins.lualine")
require("zeroknots.plugins.telescope")
require("zeroknots.plugins.nvim-cmp")
-- require("zeroknots.plugins.lsp.mason")
require("zeroknots.plugins.lsp.lspsaga")
-- require("zeroknots.plugins.lsp.lspconfig")
require("zeroknots.plugins.lsp.lsp")
require("zeroknots.plugins.lsp.lsplines")
require("zeroknots.plugins.lsp.null-ls")
require("zeroknots.plugins.autopairs")
require("zeroknots.plugins.illuminate")
require("zeroknots.plugins.dracula")
require("zeroknots.plugins.gitsigns")
require("zeroknots.plugins.rainbow")
require("zeroknots.plugins.transparent")
require("zeroknots.plugins.betterescape")
require("zeroknots.plugins.lf")
